openapi: 3.0.3
info:
  title: Data Retrieval API
  version: 1.0.0
  description: |
    The Data Retrieval API authenticates users, retrieves unprocessed email data from the database, 
    matches it with stored inquiry JSON, and returns matched data in JSON format.

    **Notes:**
    - Only unprocessed email data is returned to prevent duplicate processing.  

servers:
  - url: https://app.freightoscope.com

paths:
  /AIEmailData:
    get:
      summary: Retrieve unprocessed matched inquiry data
      description: |
        Authenticates a user, retrieves unprocessed email data, matches it with stored inquiry JSON,
        and returns matched data in JSON format.
      operationId: getInquiryData
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
          description: Username for authentication
          example: john_doe
        - name: password
          in: query
          required: true
          schema:
            type: string
          description: Password for authentication
          example: secure123
        - name: confidence
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 100
          description: Optional confidence threshold (0–100)
          example: 50
      responses:
        "200":
          description: Successful response with matched inquiry data
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: "87085099"
                        name:
                          type: string
                          example: "Ball cage"
                        qty:
                          type: string
                          example: "30"
                        length:
                          type: string
                          example: "81"
                        width:
                          type: string
                          example: "122"
                        height:
                          type: string
                          example: "89"
                        size_uom:
                          type: string
                          example: "cm"
                        origin:
                          type: string
                          example: "VNSGN"
                        destination:
                          type: string
                          example: "USCHS"
                        delivery_address:
                          type: string
                          example: "479 Trade Center Parkway, Summerville, SC 29483, USA"
                        mode:
                          type: string
                          example: "Sea"
                        commodity:
                          type: string
                          example: "Ball cage"
                        commodity_type:
                          type: string
                          example: "Machinery"
                        inco_term:
                          type: string
                          example: "DAP"
                        movement_type:
                          type: string
                          example: "Port to Door"
                        remarks:
                          type: string
                          example: "Customer requests warehouse storage and domestic trucking."
              example:
                status: success
                data:
                  - code: "87085099"
                    name: "Ball cage"
                    qty: "30"
                    length: "81"
                    width: "122"
                    height: "89"
                    size_uom: "cm"
                    origin: "VNSGN"
                    destination: "USCHS"
                    delivery_address: "479 Trade Center Parkway, Summerville, SC 29483, USA"
                    mode: "Sea"
                    commodity: "Ball cage"
                    commodity_type: "Machinery"
                    inco_term: "DAP"
                    movement_type: "Port to Door"
                    remarks: "Customer requests warehouse storage and domestic trucking."
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Invalid credentials
        "403":
          description: Unauthorized company
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Unauthorized company
        "404":
          description: No matching data found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: No matching unprocessed data found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Internal server error

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic


