openapi: 3.0.3
info:
  title: Data Retrieval API
  version: 1.0.0
  description: |
    The Data Retrieval API authenticates users, retrieves unprocessed email data from the database,
    matches it with stored inquiry JSON, and returns matched data in JSON format.
servers:
  - url: https://app.freightoscope.com
paths:
  /AIEmailData:
    get:
      summary: Retrieve unprocessed matched inquiry data
      description: |
        Authenticates a user, retrieves unprocessed email data, matches it with stored inquiry JSON, 
        and returns matched data in JSON format.
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
          description: Username for authentication
          example: john_doe
        - in: query
          name: password
          schema:
            type: string
          required: true
          description: Password for authentication
          example: secure123
        - in: query
          name: confidence
          schema:
            type: integer
            minimum: 0
            maximum: 100
          required: false
          description: Optional confidence threshold (0–100)
          example: 50
      responses:
        '200':
          description: Successful response with matched inquiry data
          content:
            application/json:
              examples:
                successExample:
                  summary: Example of successful response
                  value:
                    status: "success"
                    data:
                      - code: "87085099"
                        name: "Ball cage"
                        qty: "30"
                        length: "81"
                        width: "122"
                        height: "89"
                        size_uom: "cm"
                        origin: "VNSGN"
                        destination: "USCHS"
                        delivery_address: "479 Trade Center Parkway, Summerville, SC 29483, USA"
                        mode: "Sea"
                        commodity: "Ball cage"
                        commodity_type: "Machinery"
                        inco_term: "DAP"
                        movement_type: "Port to Door"
                        remarks: "Customer requests warehouse storage and domestic trucking."
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        code: { type: string }
                        name: { type: string }
                        qty: { type: string }
                        length: { type: string }
                        width: { type: string }
                        height: { type: string }
                        size_uom: { type: string }
                        origin: { type: string }
                        destination: { type: string }
                        delivery_address: { type: string }
                        mode: { type: string }
                        commodity: { type: string }
                        commodity_type: { type: string }
                        inco_term: { type: string }
                        movement_type: { type: string }
                        remarks: { type: string }
        '401':
          description: Invalid credentials
          content:
            application/json:
              examples:
                invalidCredentials:
                  value:
                    status: "error"
                    message: "Invalid credentials"
              schema:
                type: object
                properties:
                  status: { type: string }
                  message: { type: string }
        '403':
          description: Unauthorized company
          content:
            application/json:
              examples:
                unauthorizedCompany:
                  value:
                    status: "error"
                    message: "Unauthorized company"
              schema:
                type: object
                properties:
                  status: { type: string }
                  message: { type: string }
        '404':
          description: No matching data found
          content:
            application/json:
              examples:
                noMatchFound:
                  value:
                    status: "error"
                    message: "No matching unprocessed data found"
              schema:
                type: object
                properties:
                  status: { type: string }
                  message: { type: string }
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                internalError:
                  value:
                    status: "error"
                    message: "Internal server error"
              schema:
                type: object
                properties:
                  status: { type: string }
                  message: { type: string }
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
